name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Linting Tools
        run: pip install ruff
      - name: Run Linting
        run: ruff check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest .
      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install build tools
        run: pip install build twine
      - name: Build package
        run: python -m build
      - name: Verify package metadata
        run: twine check dist/*
      - name: Generate artifact hashes
        id: hash
        run: |
          cd dist
          echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: python-package-dist
          path: dist/
          if-no-files-found: error
          retention-days: 1
        
  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      upload-assets: true
      upload-tag-name: "python-package-dist"

  deploy:
    name: Publish to PyPI
    needs: [build, provenance]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v6
        with:
          name: python-package-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true